// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:smart_assistant/models/alarm.dart';
import 'package:smart_assistant/models/conversation.dart';
import 'package:smart_assistant/models/message.dart';
import 'package:smart_assistant/models/note.dart';
import 'package:smart_assistant/models/notification_log.dart';
import 'package:smart_assistant/models/reminder.dart';
import 'package:smart_assistant/models/user_habit.dart';
import 'package:smart_assistant/models/user_location.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(NotificationLogAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(SubtaskAdapter());
    registerAdapter(UserHabitAdapter());
    registerAdapter(UserLocationAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AlarmAdapter());
    registerAdapter(ConversationAdapter());
    registerAdapter(MessageAdapter());
    registerAdapter(NoteAdapter());
    registerAdapter(NotificationLogAdapter());
    registerAdapter(ReminderAdapter());
    registerAdapter(SubtaskAdapter());
    registerAdapter(UserHabitAdapter());
    registerAdapter(UserLocationAdapter());
  }
}
