// Mocks generated by Mockito 5.4.6 from annotations
// in smart_assistant/test/unit/chat_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:smart_assistant/models/alarm.dart' as _i7;
import 'package:smart_assistant/models/conversation.dart' as _i6;
import 'package:smart_assistant/models/message.dart' as _i5;
import 'package:smart_assistant/models/note.dart' as _i8;
import 'package:smart_assistant/models/notification_log.dart' as _i11;
import 'package:smart_assistant/models/reminder.dart' as _i9;
import 'package:smart_assistant/models/user_habit.dart' as _i10;
import 'package:smart_assistant/services/ai/ai_manager.dart' as _i12;
import 'package:smart_assistant/services/ai/ai_provider.dart' as _i13;
import 'package:smart_assistant/services/database_service.dart' as _i3;
import 'package:smart_assistant/services/nlp/nlp_engine.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNlpResponse_0 extends _i1.SmartFake implements _i2.NlpResponse {
  _FakeNlpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertMessage(_i5.Message? message) =>
      (super.noSuchMethod(
            Invocation.method(#insertMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Message>> getMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, []),
            returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
          )
          as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<void> clearMessages() =>
      (super.noSuchMethod(
            Invocation.method(#clearMessages, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertConversation(_i6.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#insertConversation, [conversation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateConversation(_i6.Conversation? conversation) =>
      (super.noSuchMethod(
            Invocation.method(#updateConversation, [conversation]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.Conversation>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i4.Future<List<_i6.Conversation>>.value(
              <_i6.Conversation>[],
            ),
          )
          as _i4.Future<List<_i6.Conversation>>);

  @override
  _i4.Future<void> deleteConversation(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Message>> getMessagesForConversation(
    String? conversationId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesForConversation, [conversationId]),
            returnValue: _i4.Future<List<_i5.Message>>.value(<_i5.Message>[]),
          )
          as _i4.Future<List<_i5.Message>>);

  @override
  _i4.Future<void> insertAlarm(_i7.Alarm? alarm) =>
      (super.noSuchMethod(
            Invocation.method(#insertAlarm, [alarm]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateAlarm(_i7.Alarm? alarm) =>
      (super.noSuchMethod(
            Invocation.method(#updateAlarm, [alarm]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAlarm(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAlarm, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.Alarm>> getAlarms() =>
      (super.noSuchMethod(
            Invocation.method(#getAlarms, []),
            returnValue: _i4.Future<List<_i7.Alarm>>.value(<_i7.Alarm>[]),
          )
          as _i4.Future<List<_i7.Alarm>>);

  @override
  _i4.Future<void> insertNote(_i8.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#insertNote, [note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateNote(_i8.Note? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateNote, [note]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNote(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNote, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i8.Note>> getNotes() =>
      (super.noSuchMethod(
            Invocation.method(#getNotes, []),
            returnValue: _i4.Future<List<_i8.Note>>.value(<_i8.Note>[]),
          )
          as _i4.Future<List<_i8.Note>>);

  @override
  _i4.Future<void> updateNoteOrder(List<_i8.Note>? notes) =>
      (super.noSuchMethod(
            Invocation.method(#updateNoteOrder, [notes]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#insertReminder, [reminder]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateReminder(_i9.Reminder? reminder) =>
      (super.noSuchMethod(
            Invocation.method(#updateReminder, [reminder]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteReminder(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReminder, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.Reminder>> getReminders() =>
      (super.noSuchMethod(
            Invocation.method(#getReminders, []),
            returnValue: _i4.Future<List<_i9.Reminder>>.value(<_i9.Reminder>[]),
          )
          as _i4.Future<List<_i9.Reminder>>);

  @override
  _i4.Future<void> updateReminderOrder(List<_i9.Reminder>? reminders) =>
      (super.noSuchMethod(
            Invocation.method(#updateReminderOrder, [reminders]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> insertHabit(_i10.UserHabit? habit) =>
      (super.noSuchMethod(
            Invocation.method(#insertHabit, [habit]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateHabit(_i10.UserHabit? habit) =>
      (super.noSuchMethod(
            Invocation.method(#updateHabit, [habit]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i10.UserHabit>> getHabitsForIntent(String? intent) =>
      (super.noSuchMethod(
            Invocation.method(#getHabitsForIntent, [intent]),
            returnValue: _i4.Future<List<_i10.UserHabit>>.value(
              <_i10.UserHabit>[],
            ),
          )
          as _i4.Future<List<_i10.UserHabit>>);

  @override
  _i4.Future<_i10.UserHabit?> getHabitByParams(
    String? intent,
    String? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getHabitByParams, [intent, params]),
            returnValue: _i4.Future<_i10.UserHabit?>.value(),
          )
          as _i4.Future<_i10.UserHabit?>);

  @override
  _i4.Future<void> insertNotificationLog(_i11.NotificationLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#insertNotificationLog, [log]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i11.NotificationLog>> getNotificationLogs() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationLogs, []),
            returnValue: _i4.Future<List<_i11.NotificationLog>>.value(
              <_i11.NotificationLog>[],
            ),
          )
          as _i4.Future<List<_i11.NotificationLog>>);

  @override
  _i4.Future<void> updateNotificationLog(_i11.NotificationLog? log) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotificationLog, [log]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotificationLog(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotificationLog, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllNotificationLogs() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotificationLogs, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserLocation(Map<String, dynamic>? locationMap) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserLocation, [locationMap]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getUserLocation, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<void> deleteUserLocation() =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserLocation, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AiManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockAiManager extends _i1.Mock implements _i12.AiManager {
  MockAiManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAvailable =>
      (super.noSuchMethod(Invocation.getter(#isAvailable), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> setApiKey(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#setApiKey, [key]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String> chat({
    required String? message,
    required bool? isTurkish,
    String? userName,
    List<_i13.ChatMessage>? conversationHistory,
    String? attachmentPath,
    String? attachmentType,
    String? weatherContext,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#chat, [], {
              #message: message,
              #isTurkish: isTurkish,
              #userName: userName,
              #conversationHistory: conversationHistory,
              #attachmentPath: attachmentPath,
              #attachmentType: attachmentType,
              #weatherContext: weatherContext,
            }),
            returnValue: _i4.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#chat, [], {
                  #message: message,
                  #isTurkish: isTurkish,
                  #userName: userName,
                  #conversationHistory: conversationHistory,
                  #attachmentPath: attachmentPath,
                  #attachmentType: attachmentType,
                  #weatherContext: weatherContext,
                }),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  void clearAllSessions() => super.noSuchMethod(
    Invocation.method(#clearAllSessions, []),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, dynamic> getProvidersStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getProvidersStatus, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [NlpEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockNlpEngine extends _i1.Mock implements _i2.NlpEngine {
  MockNlpEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NlpResponse process(
    String? input, {
    bool? isTurkish = true,
    String? userName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #process,
              [input],
              {#isTurkish: isTurkish, #userName: userName},
            ),
            returnValue: _FakeNlpResponse_0(
              this,
              Invocation.method(
                #process,
                [input],
                {#isTurkish: isTurkish, #userName: userName},
              ),
            ),
          )
          as _i2.NlpResponse);

  @override
  void resetContext() => super.noSuchMethod(
    Invocation.method(#resetContext, []),
    returnValueForMissingStub: null,
  );
}
